SELECT CHILD.ID, CHILD.GENOTYPE, PARENT.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS CHILD
LEFT JOIN
ECOLI_DATA AS PARENT
ON CHILD.PARENT_ID = PARENT.ID
WHERE PARENT.GENOTYPE IS NOT NULL
AND (CHILD.GENOTYPE & PARENT.GENOTYPE) = PARENT.GENOTYPE
ORDER BY CHILD.ID;