-- 코드를 입력하세요
SELECT DISTINCT(HISTORY.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS RENT
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
ON RENT.CAR_ID = HISTORY.CAR_ID
WHERE RENT.CAR_TYPE IN ('세단') AND HISTORY.START_DATE LIKE '2022-10%'
ORDER BY HISTORY.CAR_ID DESC;